# --- FUSION offspring ---
# parent_a: invoke_tool (agent_runtime_helpers, id=901562998491)
# parent_b: strip_think_blocks (agent_runtime_helpers, id=901562998481)
# Generated by GPT-5.5 crossover 2026-06-24
# ============================================
import copy
import json
import logging
import re
from typing import Any, Dict, List, Optional


def invoke_tool_with_content_sanitizer(
    agent,
    function_name: str,
    function_args: dict,
    effective_task_id: str,
    tool_call_id: Optional[str] = None,
    messages: list = None,
    pre_tool_block_checked: bool = False,
    skip_tool_request_middleware: bool = False,
    tool_request_middleware_trace: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """Invoke a tool after sanitizing assistant-message reasoning/XML noise."""
    logger = logging.getLogger(__name__)

    def _strip_reasoning_and_tool_xml(content: str) -> str:
        if not content:
            return ""
        content = re.sub(r"<thinking>.*?</thinking>", "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(r"<reasoning>.*?</reasoning>", "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(r"<REASONING_SCRATCHPAD>.*?</REASONING_SCRATCHPAD>", "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(r"<thought>.*?</thought>", "", content, flags=re.DOTALL | re.IGNORECASE)
        for tag_name in ("tool_call", "tool_calls", "tool_result", "function_call", "function_calls"):
            content = re.sub(rf"<{tag_name}\b[^>]*>.*?</{tag_name}>", "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(
            r"(?:(?<=^)|(?<=[\n\r.!?:]))[ \t]*<function\b[^>]*\bname\s*=[^>]*>(?:(?:(?!</function>).)*)</function>",
            "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(
            r"(?:^|\n)[ \t]*<(?:think|thinking|reasoning|thought|REASONING_SCRATCHPAD)\b[^>]*>.*$",
            "", content, flags=re.DOTALL | re.IGNORECASE)
        content = re.sub(r"</?(?:think|thinking|reasoning|thought|REASONING_SCRATCHPAD)\b[^>]*>\s*", "", content, flags=re.IGNORECASE)
        content = re.sub(r"</(?:tool_call|tool_calls|tool_result|function_call|function_calls|function)>\s*", "", content, flags=re.IGNORECASE)
        return content

    def _sanitize_messages(raw_messages: Any) -> Any:
        if not isinstance(raw_messages, list):
            return raw_messages
        cleaned = []
        for message in raw_messages:
            if not isinstance(message, dict):
                cleaned.append(message)
                continue
            new_message = dict(message)
            if str(new_message.get("role", "")).lower() == "assistant" and "content" in new_message:
                c = new_message.get("content", "")
                if isinstance(c, str):
                    new_message["content"] = _strip_reasoning_and_tool_xml(c)
                elif isinstance(c, list):
                    new_c = []
                    for part in c:
                        if isinstance(part, dict) and isinstance(part.get("text"), str):
                            p = dict(part)
                            p["text"] = _strip_reasoning_and_tool_xml(p["text"])
                            new_c.append(p)
                        else:
                            new_c.append(part)
                    new_message["content"] = new_c
            cleaned.append(new_message)
        return cleaned

    if not isinstance(function_args, dict):
        function_args = {}
    function_args = copy.deepcopy(function_args)
    if "messages" in function_args:
        function_args["messages"] = _sanitize_messages(function_args.get("messages"))

    _tool_middleware_trace = list(tool_request_middleware_trace or [])
    try:
        from hermes_cli.middleware import apply_tool_request_middleware
        if not skip_tool_request_middleware:
            _tool_request_mw = apply_tool_request_middleware(
                function_name, function_args, task_id=effective_task_id or "",
                session_id=getattr(agent, "session_id", "") or "",
                tool_call_id=tool_call_id or "",
                turn_id=getattr(agent, "_current_turn_id", "") or "",
                api_request_id=getattr(agent, "_current_api_request_id", "") or "",
            )
            function_args = _tool_request_mw.payload
            _tool_middleware_trace = list(getattr(_tool_request_mw, "trace", []) or [])
    except Exception:
        pass

    block_message = None
    if not pre_tool_block_checked:
        try:
            from hermes_cli.plugins import get_pre_tool_call_block_message
            block_message = get_pre_tool_call_block_message(
                function_name, function_args, task_id=effective_task_id or "",
                session_id=getattr(agent, "session_id", "") or "",
                tool_call_id=tool_call_id or "",
                turn_id=getattr(agent, "_current_turn_id", "") or "",
                api_request_id=getattr(agent, "_current_api_request_id", "") or "",
                middleware_trace=list(_tool_middleware_trace),
            )
        except Exception:
            pass
    if block_message is not None:
        result = json.dumps({"error": block_message}, ensure_ascii=False)
        try:
            from model_tools import _emit_post_tool_call_hook
            _emit_post_tool_call_hook(
                function_name=function_name, function_args=function_args,
                result=result, task_id=effective_task_id or "",
                session_id=getattr(agent, "session_id", "") or "",
                tool_call_id=tool_call_id or "",
                turn_id=getattr(agent, "_current_turn_id", "") or "",
                api_request_id=getattr(agent, "_current_api_request_id", "") or "",
                status="blocked", error_type="plugin_block",
            )
        except Exception:
            pass
        return result

    from hermes_cli.middleware import run_tool_execution_middleware
    def _execute(next_args: dict) -> Any:
        return _ra().handle_function_call(
            function_name, next_args, effective_task_id,
            tool_call_id=tool_call_id, session_id=agent.session_id or "",
            turn_id=getattr(agent, "_current_turn_id", "") or "",
            api_request_id=getattr(agent, "_current_api_request_id", "") or "",
            enabled_tools=list(agent.valid_tool_names) if agent.valid_tool_names else None,
            skip_pre_tool_call_hook=True, skip_tool_request_middleware=True,
            enabled_toolsets=getattr(agent, "enabled_toolsets", None),
            disabled_toolsets=getattr(agent, "disabled_toolsets", None),
            tool_request_middleware_trace=list(_tool_middleware_trace),
        )
    return run_tool_execution_middleware(
        function_name, function_args,
        lambda next_args: _execute(next_args if isinstance(next_args, dict) else function_args),
        original_args=function_args, task_id=effective_task_id or "",
        session_id=getattr(agent, "session_id", "") or "",
        tool_call_id=tool_call_id or "",
        turn_id=getattr(agent, "_current_turn_id", "") or "",
        api_request_id=getattr(agent, "_current_api_request_id", "") or "",
    )
# --- END FUSION ---