"""Controlled GeneDB mutation for proof-packet-backed promotions.

This module is intentionally narrow:
- requires a controlled_promotion_proposal.json generated by Phase 3;
- marks source-missing packets as blocked_source_missing;
- always creates a DB backup before execute=True;
- writes a mutation report and SQL-style before/after diff;
- never handles legal/security/credential auto-promotion policy by itself.
"""
from __future__ import annotations

import json
import shutil
import sqlite3
import time
from pathlib import Path
from typing import Any

SCHEMA = "PGGControlledGeneDBMutation/v0.1"
BOUNDARY = "CONTROLLED_DB_MUTATION_BACKUP_DIFF_ROLLBACK_NO_AUTO_LEGAL_SECURITY"


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%S%z")


def _backup_db(db_path: Path, outdir: Path) -> Path:
    outdir.mkdir(parents=True, exist_ok=True)
    backup = outdir / f"{db_path.name}.bak.phase4_{time.strftime('%Y%m%dT%H%M%S%z')}"
    shutil.copy2(db_path, backup)
    return backup


def _fetch(con: sqlite3.Connection, gid: str) -> dict[str, Any] | None:
    con.row_factory = sqlite3.Row
    row = con.execute(
        "SELECT gene_id,status,evidence_grade,verification_status,boundary,fitness,source_refs_json FROM evolution_genes WHERE gene_id=?",
        (gid,),
    ).fetchone()
    return dict(row) if row else None


def _append_status(old: str | None, marker: str, evidence_path: str) -> str:
    old = old or ""
    if marker in old:
        return old
    return (old + ";" if old else "") + f"{marker}:{evidence_path}"


def apply_controlled_mutation(
    db_path: str | Path,
    proposal_path: str | Path,
    completion_results_path: str | Path,
    outdir: str | Path,
    *,
    execute: bool = False,
) -> dict[str, Any]:
    """Apply or preview controlled Phase4 GeneDB mutation."""
    db = Path(db_path).expanduser()
    proposal_file = Path(proposal_path).expanduser()
    results_file = Path(completion_results_path).expanduser()
    out = Path(outdir).expanduser()
    out.mkdir(parents=True, exist_ok=True)

    proposals = json.loads(proposal_file.read_text(encoding="utf-8"))
    results = json.loads(results_file.read_text(encoding="utf-8"))
    promote_ids = {
        r.get("capability_id"): r for r in proposals
        if r.get("verdict") == "PASS_CONTROLLED_PROMOTION_PROPOSAL"
        and (r.get("risk_lane") in (None, "low_engineering"))
        and (r.get("controlled_promotion_eligible") is not False)
    }
    source_missing_ids = {
        r.get("capability_id"): r for r in results
        if r.get("verdict") == "BLOCKED_SOURCE_MISSING"
    }
    backup = _backup_db(db, out) if execute else None
    con = sqlite3.connect(str(db))
    before_after: list[dict[str, Any]] = []
    promoted = 0
    missing_marked = 0
    try:
        for gid, evidence in promote_ids.items():
            before = _fetch(con, gid)
            if not before:
                before_after.append({"gene_id": gid, "action": "PROMOTE", "status": "SKIP_NOT_FOUND"})
                continue
            verification = _append_status(before.get("verification_status"), "controlled_promotion_phase4", str(proposal_file))
            boundary = _append_status(before.get("boundary"), "proof_packet", str(evidence.get("task_id") or ""))
            if execute:
                con.execute(
                    "UPDATE evolution_genes SET status=?, evidence_grade=?, verification_status=?, boundary=? WHERE gene_id=?",
                    ("verified", "A (proof packet)", verification, boundary, gid),
                )
            after = dict(before)
            after.update({"status": "verified", "evidence_grade": "A (proof packet)", "verification_status": verification, "boundary": boundary})
            before_after.append({"gene_id": gid, "action": "PROMOTE_CONTROLLED", "before": before, "after": after})
            promoted += 1

        for gid, evidence in source_missing_ids.items():
            if gid in promote_ids:
                continue
            before = _fetch(con, gid)
            if not before:
                before_after.append({"gene_id": gid, "action": "MARK_SOURCE_MISSING", "status": "SKIP_NOT_FOUND"})
                continue
            verification = _append_status(before.get("verification_status"), "blocked_source_missing_phase4", str(results_file))
            boundary = _append_status(before.get("boundary"), "source_missing_task", str(evidence.get("task_id") or ""))
            if execute:
                con.execute(
                    "UPDATE evolution_genes SET status=?, evidence_grade=?, verification_status=?, boundary=? WHERE gene_id=?",
                    ("blocked", "D (source missing)", verification, boundary, gid),
                )
            after = dict(before)
            after.update({"status": "blocked", "evidence_grade": "D (source missing)", "verification_status": verification, "boundary": boundary})
            before_after.append({"gene_id": gid, "action": "MARK_SOURCE_MISSING", "before": before, "after": after})
            missing_marked += 1
        if execute:
            con.commit()
    finally:
        con.close()

    report = {
        "schema": SCHEMA,
        "created_at": _now(),
        "db_path": str(db),
        "proposal_path": str(proposal_file),
        "completion_results_path": str(results_file),
        "outdir": str(out),
        "db_mutation": bool(execute),
        "backup_path": str(backup) if backup else None,
        "promoted_count": promoted,
        "source_missing_marked_count": missing_marked,
        "diff_path": str(out / "mutation_diff.json"),
        "rollback_instruction": f"Restore backup over DB: cp {backup} {db}" if backup else "dry-run: no rollback needed",
        "boundary": BOUNDARY,
    }
    (out / "mutation_diff.json").write_text(json.dumps(before_after, ensure_ascii=False, indent=2), encoding="utf-8")
    (out / "mutation_summary.json").write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    return report


__all__ = ["apply_controlled_mutation"]
