"""
# --- FUSION offspring ---
# parent_a: sanitize_tool_call_arguments (agent_runtime_helpers, id=901562998479)
# parent_b: repair_tool_call (agent_runtime_helpers, id=901562998492)
# Generated by GPT-5.5 crossover 2026-06-24
"""
import json
import logging
import re
from difflib import get_close_matches
from typing import Any, Optional


def sanitize_tool_call_and_name(
    messages: list,
    agent,
    *,
    logger=None,
    session_id: str = None,
    marker: str = None,
) -> dict:
    """Preprocess assistant tool calls in-place: repair tool names and corrupted JSON arguments.

    Returns:
        {"arguments_repaired": N, "names_repaired": N}
    """
    log = logger or logging.getLogger(__name__)
    result = {"arguments_repaired": 0, "names_repaired": 0}

    if not isinstance(messages, list):
        return result

    if marker is None:
        try:
            marker = _ra().AIAgent._TOOL_CALL_ARGUMENTS_CORRUPTION_MARKER
        except Exception:
            marker = "[tool-call-arguments-corrupted]"

    valid_tool_names = getattr(agent, "valid_tool_names", None)
    if valid_tool_names is None:
        valid_tool_names = set()
    else:
        valid_tool_names = set(valid_tool_names)

    def _make_tool_result_message(function_name: str, content: str, tool_call_id: str | None) -> dict:
        try:
            return make_tool_result_message(function_name, content, tool_call_id)
        except Exception:
            msg = {"role": "tool", "content": content}
            if tool_call_id is not None:
                msg["tool_call_id"] = tool_call_id
            if function_name:
                msg["name"] = function_name
            return msg

    def _prepend_marker(tool_msg: dict) -> None:
        existing = tool_msg.get("content")
        if isinstance(existing, str):
            if not existing:
                tool_msg["content"] = marker
            elif not existing.startswith(marker):
                tool_msg["content"] = f"{marker}\n{existing}"
            return
        if existing is None:
            tool_msg["content"] = marker
            return
        try:
            existing_text = json.dumps(existing, ensure_ascii=False)
        except TypeError:
            existing_text = str(existing)
        tool_msg["content"] = f"{marker}\n{existing_text}"

    def _repair_tool_name(tool_name: str) -> str | None:
        if not tool_name or not valid_tool_names:
            return None
        for xml_sep in ('"', "'", "<", ">"):
            idx = tool_name.find(xml_sep)
            if idx > 0:
                tool_name = tool_name[:idx]
        tool_name = tool_name.strip()
        if not tool_name:
            return None

        def _norm(s: str) -> str:
            return s.lower().replace("-", "_").replace(" ", "_")
        def _camel_snake(s: str) -> str:
            return re.sub(r"(?<!^)(?=[A-Z])", "_", s).lower()
        def _strip_tool_suffix(s: str) -> str | None:
            lc = s.lower()
            for suffix in ("_tool", "-tool", "tool"):
                if lc.endswith(suffix):
                    return s[:-len(suffix)].rstrip("_- ")
            return None

        if tool_name in valid_tool_names:
            return tool_name
        lowered = tool_name.lower()
        if lowered in valid_tool_names:
            return lowered
        normalized = _norm(tool_name)
        if normalized in valid_tool_names:
            return normalized
        candidates = {tool_name, lowered, normalized, _camel_snake(tool_name)}
        for _ in range(2):
            extra = set()
            for candidate in candidates:
                stripped = _strip_tool_suffix(candidate)
                if stripped:
                    extra.add(stripped); extra.add(stripped.lower())
                    extra.add(_norm(stripped)); extra.add(_camel_snake(stripped))
            candidates |= extra
        for candidate in candidates:
            if candidate and candidate in valid_tool_names:
                return candidate
        lowered_valid = {name.lower(): name for name in valid_tool_names if isinstance(name, str)}
        normalized_valid = {_norm(name): name for name in valid_tool_names if isinstance(name, str)}
        if lowered in lowered_valid:
            return lowered_valid[lowered]
        if normalized in normalized_valid:
            return normalized_valid[normalized]
        matches = get_close_matches(lowered, list(valid_tool_names), n=1, cutoff=0.7)
        return matches[0] if matches else None

    message_index = 0
    while message_index < len(messages):
        msg = messages[message_index]
        if not isinstance(msg, dict) or msg.get("role") != "assistant":
            message_index += 1; continue
        tool_calls = msg.get("tool_calls")
        if not isinstance(tool_calls, list) or not tool_calls:
            message_index += 1; continue
        insert_at = message_index + 1
        for tool_call in tool_calls:
            if not isinstance(tool_call, dict): continue
            function = tool_call.get("function")
            if not isinstance(function, dict): continue
            original_name = function.get("name")
            if isinstance(original_name, str):
                repaired_name = _repair_tool_name(original_name)
                if repaired_name and repaired_name != original_name:
                    function["name"] = repaired_name
                    result["names_repaired"] += 1
            arguments = function.get("arguments")
            if arguments is None or arguments == "":
                function["arguments"] = "{}"; continue
            if isinstance(arguments, str) and not arguments.strip():
                function["arguments"] = "{}"; continue
            if not isinstance(arguments, str): continue
            try:
                json.loads(arguments); continue
            except json.JSONDecodeError:
                tool_call_id = tool_call.get("id")
                function_name = function.get("name", "")
                function["arguments"] = "{}"
                existing_tool_msg = None
                scan_index = message_index + 1
                while scan_index < len(messages):
                    candidate = messages[scan_index]
                    if not isinstance(candidate, dict) or candidate.get("role") != "tool": break
                    if candidate.get("tool_call_id") == tool_call_id:
                        existing_tool_msg = candidate; break
                    scan_index += 1
                if existing_tool_msg is None:
                    messages.insert(insert_at, _make_tool_result_message(
                        function_name if isinstance(function_name, str) else "", marker, tool_call_id))
                    insert_at += 1
                else:
                    _prepend_marker(existing_tool_msg)
                result["arguments_repaired"] += 1
        message_index += 1
    return result
